server:
  port: ${services.ports.user}
spring:
  application:
    name: user

  datasource:
    url: jdbc:postgresql://localhost:5432/edu_platform
    username: postgres
    password: 1

  jpa:
    properties:
      hibernate:
        default_schema: users

    hibernate:
      ddl-auto: update

    show-sql: true